package model;

public enum Major {
ACC,ANT,ART,ASL,AST,AUT,BIO,BUS,CDC,CHE,CHI,CIN,COL,COM,COT,CRJ,CSE,CST,CUL,CYB,DMA,DNC,DRF,DTE,ECO,EDU,ELT,ENG,ENS,ENV,ESC,ESL,FPT,FRE,GEO,GER,GRD,HIS,HIT,HRM,HSC,HUM,HUS,HVA,IND,INT,ITL,JPN,LAT,LAW,LIB,MAR,MAT,MED,MET,MFT,MKT,MTR,MUS,NUR,OTA,PAR,PED,PFS,PHL,PHY,PNU,POA,POL,PSY,PTA,RDG,RET,RTV,SOC,SPN,THR,TYT,VST,WST,XMB
}
